"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](bg: #8f0829)\
$username$hostname\
[](fg:#8f0829 bg:#cf284e)\
$directory\
[](fg:#cf284e bg:#e89bc4)\
$git_branch$git_commit$git_state$git_status\
[ ](bg:#e89bc4)\
[](fg:#e89bc4 bg:#ebe87b)\
$c\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$erlang\
$golang\
$haskell\
$java\
$kotlin\
$lua\
$nodejs\
$python\
$ruby\
$rust\
$swift\
$package\
[ ](bg:#ebe87b)\
[](fg:#ebe87b bg:#c8cc4b)\
$cmd_duration\
[ ](bg:#c8cc4b)\
[](fg:#c8cc4b bg:#567819)\
$time\
[](fg:#567819)
$character
"""

[username]
style_user = "bg:#8f0829 fg:#000000"
style_root = "bg:#8f0829 fg:#000000"
show_always = true
format = "[$user ]($style)"

[hostname]
style = "bg:#8f0829 fg:#000000"
format = "[\uf178  ssh: $hostname ]($style)"

[directory]
truncation_symbol = "…/"
truncation_length = 5
style = "bg:#cf284e fg:#000000"
format = "[ $path ]($style)"

[git_branch]
symbol = ""
style = "bg:#e89bc4 fg:#000000"
format = "[ $symbol $branch(:$remote_branch)]($style)"

[git_commit]
tag_symbol = " "
style = "bg:#e89bc4 fg:#000000"
format = "[ \\($hash$tag\\)]($style)"

[git_state]
style = "bg:#e89bc4 fg:#000000"
format = "[$state ($progress_current/$progress_total)]($style)"

[git_status]
style = "bg:#e89bc4 fg:#000000"
format = "[($all_status$ahead_behind)]($style)"

[c]
style = "bg:#ebe87b fg:#000000"
format = "[ $symbol($version(-$name))]($style)"

[cmake]
style = "bg:#ebe87b fg:#000000"
format = "[ $symbol($version)]($style)"

[dart]
style = "bg:#ebe87b fg:#000000"
format = "[ $symbol($version)]($style)"

[deno]
style = "bg:#ebe87b fg:#000000"
format = "[ $symbol($version)]($style)"

[dotnet]
style = "bg:#ebe87b fg:#000000"
format = "[ $symbol($version)( 🎯$tfm)]($style)"

[elixir]
style = "bg:#ebe87b fg:#000000"
format = "[ $symbol($version \\(OTP $otp_version\\))]($style)"

[erlang]
style = "bg:#ebe87b fg:#000000"
format = "[ $symbol($version)]($style)"

[golang]
style = "bg:#ebe87b fg:#000000"
format = "[ $symbol($version)]($style)"

[haskell]
style = "bg:#ebe87b fg:#000000"
format = "[ $symbol($version)]($style)"

[java]
style = "bg:#ebe87b fg:#000000"
format = "[ $symbol($version)]($style)"

[kotlin]
style = "bg:#ebe87b fg:#000000"
format = "[ $symbol($version)]($style)"

[lua]
style = "bg:#ebe87b fg:#000000"
format = "[ $symbol($version)]($style)"

[nodejs]
style = "bg:#ebe87b fg:#000000"
format = "[ $symbol($version)]($style)"

[python]
style = "bg:#ebe87b fg:#000000"
format = "[ ${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\))]($style)"

[ruby]
style = "bg:#ebe87b fg:#000000"
format = "[ $symbol($version)]($style)"

[rust]
style = "bg:#ebe87b fg:#000000"
format = "[ $symbol($version)]($style)"

[swift]
style = "bg:#ebe87b fg:#000000"
format = "[ $symbol($version)]($style)"

[package]
style = "bg:#ebe87b fg:#000000"
format = "[ $symbol($version)]($style)"

[cmd_duration]
style = "bg:#c8cc4b fg:#000000"
format = "[ $duration]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#567819 fg:#000000"
format = '[ ♥ $time ]($style)'

[character]
success_symbol = " [\uf178](fg:#8f0829) "
error_symbol = " [✘](bold red) "
