preload = /home/red/Pictures/wall_vert.png
preload = /home/red/Pictures/wall_horizontal.png
wallpaper = DP-1, /home/red/Pictures/wall_vert.png
wallpaper = DP-2, /home/red/Pictures/wall_horizontal.png
wallpaper = HDMI-A-1, /home/red/Pictures/wall_horizontal.png
